openapi: 3.0.0
info:
  version: 1.0.0
  title: TH Design
  description: TH Design
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/lios/THDesign/1.0.0
  - description: Mock dev
    url: https://ngocquang.pw/api
paths:
  /auth/login:
    post:
      summary: Login with email and password
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/register:
    post:
      summary: Register new user
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        200:
          description: Register successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  /auth/me:
    post:
      summary: Get current user info
      tags:
        - Authentication
      responses:
        200:
          description: Current user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  /products:
    post:
      summary: Create new product
      tags:
        - Product
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        200:
          description: Product detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
    get:
      summary: Get all product with pagination
      tags:
        - Product
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: size
          schema:
            type: integer
      responses:
        200:
          description: Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPageResponse'
  /products/{id}:
    get:
      summary: Get product detail by ID
      tags:
        - Product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Product detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
    CreateProductRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        published:
          type: boolean
        banner:
          type: string
          format: binary
        thumbnail:
          type: string
          format: binary
        featured_images:
          type: array
          items:
            type: string
            format: binary
    ProductDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        featured_images:
          type: string
        thumbnail:
          type: string
        banner:
          type: string
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
    ProductPageResponse:
      type: object
      properties:
        current_page:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
        from:
          type: integer
        to:
          type: integer
        per_page:
          type: integer
